### PR TITLE
Moves mech weapons to the security protolathe

### PR DESCRIPTION
**Pull request by Honkers-the-clown**
## About The Pull Request
Moves mech weapons to the security protolathe
requested by Skycinnamon

ported from https://github.com/BeeStation/BeeStation-Hornet/pull/2783

## Why It's Good For The Game
stops non-antag roboticists from becoming the ultimate validhunting machine

## Changelog
:cl:
balance: moved mech weapons to the sec protolathe
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
Personally, I don't like it, sec protolathe will now be huge bloat with 20+ ammo types and weapons at late-game.
I'd consider adding some restrictions to exosuit fabricator instead, but of course, that'd mean more shitcode.

**Comment by BootlegBow** [comment]
> Personally, I don't like it, sec protolathe will now be huge bloat with 20+ ammo types and weapons at late-game.
> I'd consider adding some restrictions to exosuit fabricator instead, but of course, that'd mean more shitcode.

Something like having to swipe an ID with armoury access on the exofab before being able to print could work well

**Comment by EgorDinamit** [comment]
> Something like having to swipe an ID with armoury access on the exofab before being able to print could work well

That could work well.

**Comment by Honkers-the-clown** [comment]
^^

**Pull request closed without merging**
