### PR TITLE
/tg/ merge

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Merges all /tg/ PRs **up until Combat Mode.**

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
This messes with martial arts, so I'll have to wait for this to be merged, and update #12 with it.

**Comment by EgorDinamit** [comment]
> This messes with martial arts, so I'll have to wait for this to be merged, and update #12 with it.

How does it mess with martial arts? I didn't merge combat mode.

**Comment by Samuuu3** [comment]
> > This messes with martial arts, so I'll have to wait for this to be merged, and update #12 with it.
> 
> How does it mess with martial arts? I didn't merge combat mode.

Why wouldn't you merge combat mode?

**Comment by EgorDinamit** [comment]
A lot of people have concerns about combat mode, and I am pretty sure it is still not ready, so I'll wait for it to be complete before merging.
So, this update only includes everything that was before intents removal.

**Pull request merged**
