### PR TITLE
expands chef's cqc area to the bar

### PR DESCRIPTION
**Pull request by Honkers-the-clown**
## About The Pull Request

expands the cook's cqc area to the bar

## Why It's Good For The Game

helps cooks serve food in the bar without getting mugged

## Changelog
:cl:
Balance: expands cook's cqc area to the bar
/:cl:

### CODE REVIEW

**Review by EgorDinamit — APPROVED** [review]
Seems fine to me.
(Can't wait to see bartenders dying to traitor cooks)

**Comment by Honkers-the-clown** [comment]
> Seems fine to me.
> (Can't wait to see bartenders dying to traitor cooks)

:Flushed:

**Comment by JohnFulpWillard** [comment]
You know, this change was done on TG. We can get it with a TG update

**Comment by EgorDinamit** [comment]
If I am not wrong, it got reverted on /tg/, and even then, we're still not 100% positive on merging with /tg/.

**Comment by JohnFulpWillard** [comment]
> 
> 
> If I am not wrong, it got reverted on /tg/, and even then, we're still not 100% positive on merging with /tg/.

It hasnt been reverted

**Pull request merged**
