### PR TITLE
Void Technician (Revamp of Space Explorer)

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request

Adds a new Job: Void Technician and adds it's jumpsuit and hardsuit into the game.

## Why It's Good For The Game

Job Description:
Void Technician
Make the engineers jealous that you start with a hardsuit. Run into space with nothing but some metal rods. Forget your oxygen and die immediately. Pretend to be an engineer and then accidentally dust yourself after you have no clue how to start the engine.
Make the miners cry after you find better loot than them, immediately die to a single laser when you realize that you have awful armor and no way of defending yourself other than the shitty makarov that just made the miners jealous. Bring back super awesome machinery and make the CE cry that she doesn't know how to run a TEG. 

Roundstart they get:
A fast, but very weak hardsuit.
Metal rods to construct Highways
Standard engineering toolbelt
Science and Engineering Comms, for both research and engineering, in a special Headset that lets them talk to the station while not nearby.

At Tegustation we have an abundance of unique and cool space ruins, this job allows for 3 things.

1. Void technician adds a job solely meant to explore space and all of our unique ruins.
2. Unlike the old Space Explorer, the Void Tech has an important job: To bring back machinery!
This allows us to create and re-add old machinery that may have been too powerful for general use, but when put into a rare ruin, then it will add in an awesome powerboost to the station, and dynamically change the round
3. This job's other role, to build and expand space highways, adds a real presence to the station in space that it really didn't have before

This Job is a great fit for our Ruin-heavy server, and fills the role of "Space Explorer" quite well.

## Changelog
:cl:
add: Added Void Technician as a playable job
add: Added Jumpsuit and Hardsuit
imageadd: added Voidtech's stuff as images
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
Sprites might need some changes, I'd say, and they definitely need a dedicated spawn location.
I'd make them spawn in a "space ruin", so we can avoid editing /tg/ maps and save us from merge conflicts.

If you are okay with it, I'll make a quick map for said "ruin".

**Comment by Kitsunemitsu** [comment]
> 
> 
> Sprites might need some changes, I'd say, and they definitely need a dedicated spawn location.
> I'd make them spawn in a "space ruin", so we can avoid editing /tg/ maps and save us from merge conflicts.
> 
> If you are okay with it, I'll make a quick map for said "ruin".

Sounds good! I Just got the bones here. I'm not a spriter, and it's an easy one to fix later.
This hardsuit is just here until we get a better looking one

**Comment by JohnFulpWillard** [comment]
1) I personally dont want to add more jobs before the TG Update. Deputies is already gonna be an incredible pain
2) I dont like how a Curator 2 works under the CE. Why not just be under the HoP but have Engineering access? I'm just not a fan

**Comment by EgorDinamit** [comment]
I don't care if it's added after or before /tg/ merge, it's my task anyway.
I'd consider making them work for a service/supply department or nobody(directly answering to captain?) at all since engineering is more about the station's integrity.

**Comment by BootlegBow** [comment]
From what I can tell, they're under Engineering since they're supposed to bring back and construct machines they find as well as build space highways

**Review by EgorDinamit — APPROVED** [review]
Looks pretty good now, in my opinion.
I'll merge in a few days once everything is 100% finished and working.

**Pull request merged**
