### PR TITLE
Improves engineering bounties

### PR DESCRIPTION
**Pull request by BootlegBow**
## About The Pull Request

Removes a ton of the complicated gases from the Engineering bounty list, and adds a few new basic gases and machines to the list.

## Why It's Good For The Game

Previously, engineers could only get bounties that are literally impossible for them to complete (i.e. Zauker). This fixes that.

## Changelog
:cl:
add: New engi bounties
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
You should instead add these to a separate modular folder with all the tegu-only bounties, and not delete tg code itself, either

**Comment by BootlegBow** [comment]
So it turns out that it's pretty much completely broken and I have no clue why. I'll keep trying to see if I can fix it

**Comment by BootlegBow** [comment]
Alright, should be working now

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Your "overwrites" don't do anything, you should've added "return" to each one.
And I'd suggest to keep them in or replace with _medium-difficulty_ gases: Tritium, Hydrogen, BZ and Pluoxium.

And look to #9. You'd have to move code files to proper folder.

**Comment by BootlegBow** [comment]
shit alright

**Comment by BootlegBow** [comment]
I'll fix the overwrites and add tritium, BZ and hydrogen

**Comment by BootlegBow** [comment]
@EgorDinamit should be alright now if you wouldn't mind having a look

**Comment by BootlegBow** [comment]
shit

**Comment by EgorDinamit** [comment]
Remove easy gases(Oxygen, CO2, Nitrogen, Plasma, etc) from here.

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Remove easy gases from here: Nitrogen, Oxygen, H2O, CO2 and Plasma. Those are available round-start and can be simply ordered from cargo.
Add pluoxium/tritium in, this one is quite easy to make and isn't available round-start.

**Comment by BootlegBow** [comment]
Pluoxium and tritium are both on the bounty list already, since I haven't overwritten any of the original ones

**Comment by BootlegBow** [comment]
I'm also fairly certain plasma cannot be ordered from cargo

**Comment by EgorDinamit** [comment]
Great, then remove all round-start available gases.

**Comment by BootlegBow** [comment]
Smartfridges can definitely be unwrenched

**Comment by BootlegBow** [comment]
Also, H2O isn't a roundstart gas, unless we're counting janitor's closets

**Comment by EgorDinamit** [comment]
The thing is, you can't make H2O(sort of), but you can order it from cargo or get from janitor's room.
I guess you can unwrench smartfridge, maybe.

**Review by EgorDinamit — APPROVED** [review]

**Comment by BootlegBow** [comment]
H2O can be easily made in turbine, but the idea of people tiding the jani office for it makes it a bad idea for me to re-add

**Pull request merged**
